lidar_odometry_node:
  ros__parameters:
    # Frame Configuration
    base_frame: "base_link"
    odom_frame: "odom" 
    map_frame: "map"

    # Publishing Options
    publish_tf: true
    publish_features: true
    publish_map: true
    
    # Configuration File Path
    config_file: "$(find lidar_odometry_ros)/../../lidar_odometry/config/kitti.yaml"
    
    # Logging
    console_output: true
